language: python

sudo: false

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOX_ENV=py36-django3.2-drf3.11
    - python: 3.6
      env: TOX_ENV=py36-django3.2-drf3.12
    - python: 3.6
      env: TOX_ENV=py36-django3.2-drf3.13
    - python: 3.7
      env: TOX_ENV=py37-django3.2-drf3.11
    - python: 3.7
      env: TOX_ENV=py37-django3.2-drf3.12
    - python: 3.7
      env: TOX_ENV=py37-django3.2-drf3.13
    - python: 3.8
      env: TOX_ENV=py38-django3.2-drf3.11
    - python: 3.8
      env: TOX_ENV=py38-django3.2-drf3.12
    - python: 3.8
      env: TOX_ENV=py38-django3.2-drf3.13
    - python: 3.9
      env: TOX_ENV=py39-django3.2-drf3.11
    - python: 3.9
      env: TOX_ENV=py39-django3.2-drf3.12
    - python: 3.9
      env: TOX_ENV=py39-django3.2-drf3.13
    - python: 3.10
      env: TOX_ENV=py310-django3.2-drf3.11
    - python: 3.10
      env: TOX_ENV=py310-django3.2-drf3.12
    - python: 3.10
      env: TOX_ENV=py310-django3.2-drf3.13
    - python: 3.6
      env: TOX_ENV=py36-django4.0-drf3.13
    - python: 3.7
      env: TOX_ENV=py37-django4.0-drf3.13
    - python: 3.8
      env: TOX_ENV=py38-django4.0-drf3.13
    - python: 3.9
      env: TOX_ENV=py39-django4.0-drf3.13
    - python: 3.10
      env: TOX_ENV=py310-django4.0-drf3.13

install:
  - pip install tox

script:
    - tox -e $TOX_ENV

branches:
  only:
    - master
